### ISSUE TITLE
Move AGL auxiliary layers to meta-xt-images

### ISSUE THREAD

**Issue by andr2000** [xen-troops/meta-xt-prod-ces2018#42]
Move from recipes-domd/agl/inc/domd-agl-image.inc:
`XT_QUIRK_BB_ADD_LAYER += "\
    meta-virtualization \
    meta-selinux \
    meta-clang \
"

SRC_URI_append = " \
    git://git.yoctoproject.org/meta-virtualization;destsuffix=repo/meta-virtualization;branch=morty \
    git://git.yoctoproject.org/meta-selinux;destsuffix=repo/meta-selinux;branch=morty \
    git://github.com/kraj/meta-clang.git;destsuffix=repo/meta-clang;branch=morty \
"
`
to meta-xt-images, but let meta-xt-prod-ces2018 select branch, e.g. morty in this case

**Comment by iartemenko** [comment]
Fixed in: c77554354f5da1390c9bb7bcdde11010a7bd1dac
meta-xt-images: e7f46b4151b9116b7b1b014c6488f68ce06e868c
